apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s3t0mk814-nodejs 
  janus-idp.io/tekton: s3t0mk814-nodejs
  backstage.io/kubernetes-id: s3t0mk814-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s3t0mk814-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  